# Generated by Django 6.0.1 on 2026-01-17 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('EMAIL', 'Email'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('TEXTAREA', 'Text Area'), ('SELECT', 'Select Dropdown'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio Button'), ('FILE', 'File Upload'), ('PHONE', 'Phone'), ('URL', 'URL'), ('DECIMAL', 'Decimal')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pattern', models.CharField(blank=True, max_length=500, null=True)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(default='Employee Form', max_length=255)),
                ('form_description', models.TextField(blank=True)),
                ('fields', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('dynamic_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEAVE', 'On Leave')], default='ACTIVE', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='api_employe_email_5d0ffb_idx'), models.Index(fields=['department'], name='api_employe_departm_a88d93_idx'), models.Index(fields=['status'], name='api_employe_status_a8c1a8_idx')],
            },
        ),
    ]
